from enum import Enum


class HitStep(Enum):
    RETRIEVED = "RETRIEVED"
    DOUBLED = "DOUBLED"
    NOT_DOUBLED = "NOT_DOUBLED"
    FILE_SECTION_RETRIEVED = "FILE_SECTION_RETRIEVED"
    RELEVANCE_GRADED = "RELEVANCE_GRADED"
    RELATED_DATA_GATHERED = "RELATED_DATA_GATHERED"
