from enum import Enum


class SearchStep(Enum):
    PLANNED = "PLANNED"
    RETRIEVED = "RETRIEVED"
    CLEANED = "CLEANED"
    RELEVANCE_GRADED = "RELEVANCE_GRADED"
    RELATED_DATA_GATHERED = "RELATED_DATA_GATHERED"
